version: "3"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: internhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  frontend:
    build: . 
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis